name: Check tests on PRs - pnpm CI

on:
  push:
    branches: [ "main", "dev" ]
    paths:
      - "apps/web/**"
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - "apps/web/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        working-directory: apps/web
        run: pnpm install

      - name: Run tests
        working-directory: apps/web
        run: pnpm test
        env:
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PRIVATE_SUPABASE_SERVICE_ROLE: ${{ secrets.NEXT_PRIVATE_SUPABASE_SERVICE_ROLE }}